spring:
  application:
    name: Trendyol Meetup CQRS API
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

swagger:
  host:
    url: localhost:8080
    path:

server:
  port: 8080
